# Generated by Django 4.1.5 on 2023-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_bookingdate_alter_booking_no_of_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(verbose_name=['%m/%d/%Y %H:%M']),
        ),
    ]
