# Generated by Django 4.1.5 on 2023-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Inventory',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
